name: Currency Build

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Name of the package to build'
        required: true
      version:
        description: 'Version of the package'
        required: true
      validate_build_script:
        description: 'Run build validation script'
        required: true
        default: 'false'
      wheel_build:
        description: 'Create wheel for different Python versions'
        required: true
        default: 'false'
      build_docker:
        description: 'Build docker image'
        required: true
        default: 'false'
      enable_trivy:
        description: 'Enable Trivy scan'
        required: true
        default: 'true'
      enable_syft:
        description: 'Enable Syft scan'
        required: true
        default: 'true'
      enable_grype:
        description: 'Enable Grype scan'
        required: true
        default: 'true'
      unique_id:
        description: 'Unique ID for the build'
        required: false
        default: 'None'

jobs:
  build_info:
    uses: ./.github/workflows/build-info.yaml
    with:
      package_name: ${{ inputs.package_name }}
      version: ${{ inputs.version }}
      validate_build_script: ${{ inputs.validate_build_script }}
      wheel_build: ${{ inputs.wheel_build }}
      build_docker: ${{ inputs.build_docker }}
      enable_trivy: ${{ inputs.enable_trivy }}
      enable_syft: ${{ inputs.enable_syft }}
      enable_grype: ${{ inputs.enable_grype }}
      unique_id: ${{ inputs.unique_id }}

  build:
    needs: build_info
    runs-on: ubuntu-24.04-ppc64le-p10
    steps:
      - name: Print Hello World
        run: echo "Hello World"

      - name: Print length of GHA_PAT_SEC (safely)
        run: |
          echo "Length of GHA_PAT_SEC: ${#GHA_PAT_SEC}"
        env:
          GHA_PAT_SEC: ${{ secrets.GHA_PAT_SEC }}
    # uses: ./.github/workflows/build.yaml
    # with:
    #   validate_build_script: ${{ inputs.validate_build_script }}
