name: Hello and Secret Length

on:
  workflow_call:
    inputs:
      validate_build_script:
        required: true
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-24.04-ppc64le-p10
    steps:
      - name: Print Hello World
        run: echo "Hello World"

      - name: Print length of GHA_PAT_SEC (safely)
        run: |
          echo "Length of GHA_PAT_SEC: ${#GHA_PAT_SEC}"
        env:
          GHA_PAT_SEC: ${{ secrets.GHA_PAT_SEC }}
